# Generated by Django 3.2.9 on 2021-11-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
